Repository Scarlet-Reach/Scarlet-Reach, pull requests merged in 2025-07, with the labels that each got.

#65 Gives inquisitor a psycross
  code/modules/jobs/job_types/roguetown/Inquisition/puritan.dm
Labels: testmerged

#22 Ports over wretches being able to be supernatural monsters
  code/modules/antagonists/roguetown/villain/vampire.dm
  code/modules/antagonists/roguetown/villain/werewolf/werewolf.dm
  code/modules/jobs/job_types/roguetown/adventurer/wretch.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/grabbing.dm
Labels: testmerged

#64 Bug fix for commit #9 - Properly stops excommunicated healing
  code/modules/spells/roguetown/acolyte/astrata.dm
  code/modules/spells/roguetown/acolyte/general.dm
Labels: testmerged

#62 Ports Emberwine
  code/datums/sexcon/sexcon.dm
  code/datums/sexcon/sexcon_reagents.dm
  code/datums/status_effects/rogue/debuff.dm
  code/modules/cargo/packsrogue/bathmatron/drugs.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/roguetown/roguecrafting/alchemy/alch_cauldron_recipes.dm
  code/modules/roguetown/roguejobs/alchemist/container.dm
  code/modules/roguetown/roguemachine/drugmachine.dm
  goon/browserassets/css/browserOutput.css
  icons/mob/screen_alert.dmi
  roguetown.dme
Labels: testmerged

#10 Resubmit of the daring twit PR
  code/modules/jobs/job_types/roguetown/youngfolk/prince.dm
Labels: testmerged

#5 Update scomm.dm
  code/modules/roguetown/roguemachine/scomm.dm
Labels: testmerged

#55 Dracons can disable snouts, more wing/tail choices
  code/modules/client/customizer/customizers/organ/snout.dm
  code/modules/client/customizer/customizers/organ/tail.dm
  code/modules/client/customizer/customizers/organ/wings.dm
Labels: testmerged

#57 Brutes now get a choice of weapon like barbs
  code/modules/jobs/job_types/roguetown/Inquisition/orthoclasses/disciple.dm
Labels: testmerged

#39 Cure Rot miracle spell should revive dead player back regardless of who casts it.
  code/modules/spells/roguetown/acolyte/pestra.dm
Labels: testmerged

#127 Removes dimension limits on "alternate" "headshot"
  code/modules/client/preferences.dm
Labels: testmerged

#148 Buffs Killer's Ice back to what it was
  code/modules/roguetown/roguecrafting/alchemy/reagents.dm
Labels: Balance

#203 Zizo poison
  code/modules/cargo/packsrogue/merchant/merchant_potions.dm
  code/modules/roguetown/roguecrafting/alchemy.dm
  code/modules/roguetown/roguecrafting/alchemy/alch_cauldron_recipes.dm
  code/modules/roguetown/roguecrafting/alchemy/alch_items.dm
  code/modules/roguetown/roguecrafting/alchemy/reagents.dm
Labels: testmerged

#88 Priest rework
  code/__DEFINES/traits.dm
  code/controllers/subsystem/rogue/devotion.dm
  code/datums/components/crafting/crafting.dm
  code/datums/gods/curses.dm
  code/datums/status_effects/rogue/debuff.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/datums/stress/negative_events.dm
  code/datums/stress/positive_events.dm
  code/game/turfs/open/water.dm
  code/modules/jobs/job_types/roguetown/church/priest.dm
  code/modules/mob/living/roguetownprocs.dm
  code/modules/roguetown/roguejobs/blacksmith/tools.dm
  code/modules/spells/roguetown/acolyte/pestra.dm
  code/modules/spells/roguetown/priest.dm
  code/modules/surgery/surgeries_hearth/revival.dm
  roguetown.dme
Labels: testmerged

#198 Disables round start werewolfs
  code/modules/events/antagonist/solo/werewolf.dm
Labels: testmerged

#77 Staff of the shepard has cast time reduction and applies firestacks
  code/game/objects/items/rogueweapons/melee/polearms.dm
Labels: testmerged, Balance

#236 Guillotine revisit
  code/datums/stress/negative_events.dm
  code/datums/stress/positive_events.dm
  code/game/objects/structures/guillotine.dm
  code/modules/surgery/bodyparts/bodypart_dismemberment.dm
Labels: testmerged

#223 GRENZELHOFT COLORPLEX: limits access to the color wheel, but expands default colors; adds the Tailor's Swatchbook
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/game/objects/items/rogueitems/books.dm
  code/modules/cargo/packsrogue/merchant/luxury.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/pilgrim/seamstress.dm
  code/modules/jobs/job_types/roguetown/mercenaries/classes/warscholar.dm
  code/modules/jobs/job_types/roguetown/yeomen/tailor.dm
  code/modules/roguetown/roguejobs/tailor/dyer.dm
  icons/roguetown/items/books.dmi
Labels: testmerged

#187 Mouthgrabs now take coverage into account, in line with strangling
  code/modules/clothing/rogueclothes/mask.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: testmerged, Balance

#297 Unapologetic salt PR
  code/modules/spells/spell_types/wizard/utility/message.dm
  code/modules/spells/spell_types/wizard/utility/mindlink.dm
Labels: testmerged, Balance

#308 Giant's strength applies strength uncapped for the duration
  code/modules/spells/spell_types/wizard/buffs_debuffs/giants_strength.dm
Labels: Testmerged

#328 Cmp timer runtimes fix i hope [Test merge first]
  code/controllers/subsystem/timer.dm
Labels: Testmerged, Bug Fix

#270 Fixes Amazon adventurer class
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/warrior.dm
Labels: Testmerged, Bug Fix

#344 Adds in the disgraced noble trait
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/antag/hedgeknight.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/wretch/deserter.dm
  code/modules/jobs/job_types/roguetown/peasants/hostage.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Code

#348 LOOC shows true name even when masked
  modular_hearthstone/code/interface/LOOC.dm
Labels: Testmerged

#247 Veteran! - Additional Retired Mercenary Backgrounds and Properly Adjusted Races
  code/modules/jobs/job_types/roguetown/garrison/veteran.dm
Labels: Testmerged
